"""Structured customer-intent schema for reliable order mutation."""

from __future__ import annotations

from .models import OrderIntent

INTENT_ADD_ITEM = "add_item"
INTENT_REMOVE_ITEM = "remove_item"
INTENT_REPLACE_ITEM = "replace_item"
INTENT_MODIFY_ITEM = "modify_item"
INTENT_CHANGE_QUANTITY = "change_quantity"
INTENT_CHANGE_FLAVOR = "change_flavor"
INTENT_CHANGE_COOK_PREFERENCE = "change_cook_preference"
INTENT_CHANGE_PIECE_PREFERENCE = "change_piece_preference"
INTENT_ASK_TOTAL = "ask_total"
INTENT_ASK_MENU = "ask_menu"
INTENT_CONFIRM_ORDER = "confirm_order"
INTENT_CANCEL_ORDER = "cancel_order"
INTENT_RESTART_ORDER = "restart_order"
INTENT_HANDOFF_REQUEST = "handoff_request"
INTENT_COMPLAINT = "complaint"
INTENT_UNKNOWN = "unknown"

SUPPORTED_INTENTS = {
    INTENT_ADD_ITEM,
    INTENT_REMOVE_ITEM,
    INTENT_REPLACE_ITEM,
    INTENT_MODIFY_ITEM,
    INTENT_CHANGE_QUANTITY,
    INTENT_CHANGE_FLAVOR,
    INTENT_CHANGE_COOK_PREFERENCE,
    INTENT_CHANGE_PIECE_PREFERENCE,
    INTENT_ASK_TOTAL,
    INTENT_ASK_MENU,
    INTENT_CONFIRM_ORDER,
    INTENT_CANCEL_ORDER,
    INTENT_RESTART_ORDER,
    INTENT_HANDOFF_REQUEST,
    INTENT_COMPLAINT,
    INTENT_UNKNOWN,
}

__all__ = [
    "OrderIntent",
    "INTENT_ADD_ITEM",
    "INTENT_REMOVE_ITEM",
    "INTENT_REPLACE_ITEM",
    "INTENT_MODIFY_ITEM",
    "INTENT_CHANGE_QUANTITY",
    "INTENT_CHANGE_FLAVOR",
    "INTENT_CHANGE_COOK_PREFERENCE",
    "INTENT_CHANGE_PIECE_PREFERENCE",
    "INTENT_ASK_TOTAL",
    "INTENT_ASK_MENU",
    "INTENT_CONFIRM_ORDER",
    "INTENT_CANCEL_ORDER",
    "INTENT_RESTART_ORDER",
    "INTENT_HANDOFF_REQUEST",
    "INTENT_COMPLAINT",
    "INTENT_UNKNOWN",
    "SUPPORTED_INTENTS",
]
